### PR TITLE
Site had to be taken down because of a DMCA

### PR DESCRIPTION
**Pull request by itsmechinmoy**

### CODE REVIEW

**Comment by MarshMeadow** [comment]
so what do we do?

**Comment by itsmechinmoy** [comment]
> so what do we d

im hosting it on netlify 🤷🏻
And today rebel said having a site was a bad idea but ig the dmca he got was probably because of mentioning extensions in the install page
The app will get dmca too if he doesn't  removes the hard-coded repos

**Comment by MarshMeadow** [comment]
> > so what do we d
> 
> im hosting it on netlify 🤷🏻 And today rebel said having a site was a bad idea but ig the dmca he got was probably because of mentioning extensions in the install page The app will get dmca too if he doesn't removes the hard-coded repos

ah i see yeah yeah even if it dose get dmca i or someone else would continue it..

**Comment by itsmechinmoy** [comment]
> > > so what do we d
> > 
> > im hosting it on netlify 🤷🏻 And today rebel said having a site was a bad idea but ig the dmca he got was probably because of mentioning extensions in the install page The app will get dmca too if he doesn't removes the hard-coded repos
> 
> ah i see yeah yeah even if it dose get dmca i or someone else would continue it..

Im hosting it till ibo makes a better one
<https://dantotsu.netlify.app/alpha>

**Pull request closed without merging**
